
#include "opencv2/opencv.hpp"

#include <iostream>
#include <sstream>

using namespace cv;
using namespace std;

// run with "vtest.avi" 

int main(int argc, char** argv)
{
    Mat fgMaskMOG2;                  // fg mask fg mask generated by MOG2 method
    Ptr<BackgroundSubtractor> pMOG2; // MOG2 Background subtractor

    VideoCapture cap(argv[1]); // open the video from args 1
    if (!cap.isOpened())       // check if we succeeded
        return -1;

    // create Background Subtractor objects
    pMOG2 = createBackgroundSubtractorMOG2(); // MOG2 approach

    namedWindow("frame", 1);
    namedWindow("FG Mask MOG 2");
    for (;;)
    {
        Mat frame;
        cap >> frame; // get a new frame from camera
        Mat canny_output;
        pMOG2->apply(frame, fgMaskMOG2);

        threshold(fgMaskMOG2, fgMaskMOG2, 50, 255, THRESH_BINARY);
        morphologyEx(fgMaskMOG2, fgMaskMOG2, MORPH_OPEN, getStructuringElement(MORPH_RECT, Size(5, 5)));
        imshow("FG Mask MOG 2", fgMaskMOG2);

        vector<vector<Point>> contours;
        vector<Vec4i> hierarchy;
        findContours(fgMaskMOG2, contours, hierarchy, RETR_EXTERNAL, CHAIN_APPROX_SIMPLE);
        vector<vector<Point>> contours_poly(contours.size());
        vector<Rect> boundRect(contours.size());
        int j = 0;

        for (size_t i = 0; i < contours.size(); i++)
        {
            approxPolyDP(contours[i], contours_poly[j], 5, true);
            if (contours_poly[j].size() > 3.5)
            {
                boundRect[j] = boundingRect(Mat(contours_poly[j]));
                j++;
            }
        }

        Mat drawing = Mat::zeros(fgMaskMOG2.size(), CV_8UC3);
        for (size_t i = 0; i < contours.size(); i++)
            drawContours(drawing, contours, (int)i, Scalar(0, 200, 0), 2, LINE_8, hierarchy, 0);

        for (int i = 0; i < j; i++)
        {
            rectangle(frame, boundRect[i].tl(), boundRect[i].br(), Scalar(0, 0, 200), 2, 8, 0);
            rectangle(drawing, boundRect[i].tl(), boundRect[i].br(), Scalar(0, 0, 200), 2, 8, 0);
        }

        imshow("Contours", drawing);
        imshow("frame", frame);

        if (waitKey(30) >= 0)
            break;
    }
    return 0;
}